AWSTemplateFormatVersion: 2010-09-09
Description: An RDS instance

MyDB:
  Type: AWS::RDS::DBInstance
  Properties:
    DBSecurityGroups:
    - Ref: MyDbSecurityByEC2SecurityGroup
    - Ref: MyDbSecurityByCIDRIPGroup
    AllocatedStorage: '1'
    DBInstanceClass: db.t2.small
    Engine: PostgreSQL
    MasterUsername: postgres
    MasterUserPassword: ${{ secrets.POSTGRES_PASSWORD }}
  DeletionPolicy: Snapshot