AWSTemplateFormatVersion: 2010-09-09
Description: An RDS instance

Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: 
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      Engine: postgres
      MasterUsername: !Sub '{{resolve:ssm:/database/postgres/username}}'
      MasterPassword: !Sub '{{resolve:ssm:/database/postgres/password}}'
    DeletionPolicy: Retain

  Outputs: 
    DatabaseName: 
      Value: !Ref Database

    DatabaseURL: 
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - Database
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - Database
                - Endpoint.Port
            - '/'
            - !Ref Database